### PR TITLE
draft: add utf8 and iso 8859-1 header decoding

### LINKED ISSUE #78: Utf8 and iso 8859-1 (Latin string) decoding for headers
Headers can be encoded and we don't currently handle this.

I have a hacky implementation I will submit as a WIP pr but someone else will need to polish it as I won't have time to get it over the line.

### PR DESCRIPTION
**Pull request by Laeeth**
Sorry for the code.  It's what I could manage in the time I had. 
Please take ownership for getting it over the line. @otrho 
closes #78

### CODE REVIEW

**Comment by otrho** [comment]
I kinda rewrote it in the end to be a bit less fiddly.  Hope it still fits what you had in mind.

**Review by otrho — CHANGES_REQUESTED** [review]
Please confirm my changes are OK.

**Comment by Laeeth** [comment]
Nice.  Lgtm

**Comment by adamdruppe** [comment]
so this project depends on my email lib and this kind of stuff is already in there fyi, it does quoted-printable decoding, charset translation (it handles a lot of different thing). Unless it is buggy lol.

 convertToUtf8Lossy(decodeQuotedPrintable(textMessageBody), charset);

that kind of thing. So if you have trouble in the future we might be able to use some of those functions.

**Pull request merged**
