### PR TITLE
Github actions

### PR DESCRIPTION
**Pull request by maxhaton**
First go. My luck suggests something will fail but I was able to run it locally. CodeCov thing apparently will just work, someone will need to fiddle with the key if not.

### CODE REVIEW

**Comment by maxhaton** [comment]
@skoppe

**Comment by skoppe** [comment]
Looks good, but needs to be `.yml`. Can also delete the travis CI file.

**Comment by maxhaton** [comment]
> Looks good, but needs to be `.yml`. Can also delete the travis CI file.

That would explain why it didn't pick it up. I used `act` to check it ran locally and that does look for .yaml

**Comment by skoppe** [comment]
Hmm, it still doesn't run. Maybe my suspicion around .yml/.yaml was wrong.

Perhaps it doesn't work because you added a workflow as an external contributer and github blocks running actions in that case to prevent you installing cryptominers or whatever that run on symmetry's repo.

In that case merging it should solve it.

Let me push some other things later this weekend then solve this.

**Comment by skoppe** [comment]
Great! nice.

**Pull request merged**
