### PR TITLE
Windows CI: Replace AppVeyor by GitHub Actions

### PR DESCRIPTION
**Pull request by kinke**

### CODE REVIEW

**Comment by kinke** [comment]
@maxhaton: It's working now with the `LIB` env var on Windows - with LDC, but not with DMD; AFAICT, DMD overwrites `LIB` at some point before `link.exe` gets it.

**Comment by maxhaton** [comment]
How irritating

**Comment by maxhaton** [comment]
Looks like it might be set in one of the .ini files for optlink

**Comment by kinke** [comment]
Yep: https://issues.dlang.org/show_bug.cgi?id=22707

**Comment by kinke** [comment]
Ugly workaround for the DMD Windows job is in place, PR ~green.

**Comment by skoppe** [comment]
Awesome work guys!

**Comment by skoppe** [comment]
It would be interesting if what we learned here can be applied at https://github.com/symmetryinvestments/rabbitmq-d/pull/21

**Pull request merged**
